config/routes.rb
Rails.application.routes.draw do
  resources :sensors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# Model defaults
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sensor.rb
# Information about a sensor
class Sensor < ApplicationRecord
  validates :label, :model, presence: true
  validates :node_id, :pm_sensor_id, :temp_rh_sensor_id, :community_registration_id, numericality: true
  validates :label, :node_id, :pm_sensor_id, :temp_rh_sensor_id, :community_registration_id, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sensors_controller.rb
# Controller to manage sensors
class SensorsController < ApplicationController
  before_action :set_sensor, only: %i[show edit update destroy]

  # GET /sensors or /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors/1 or /sensors/1.json
  def show; end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit; end

  # POST /sensors or /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: "Sensor was successfully created." }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1 or /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: "Sensor was successfully updated." }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1 or /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: "Sensor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_sensor
    @sensor = Sensor.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def sensor_params
    params.fetch(:sensor, {}).permit(
      :label,
      :model,
      :node_id,
      :pm_sensor_id,
      :temp_rh_sensor_id,
      :community_registration_id,
      :active
    )
  end
end

app/helpers/application_helper.rb
# Application Helper
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SensorCommunityCalne</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sensors/_form.html.erb
<%= form_with(model: sensor) do |form| %>
  <% if sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
        <% sensor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label :label, "Label" %>
  <%= form.text_field :label %>

  <%= form.label :model, "Model" %>
  <%= form.text_field :model %>

  <%= form.label :node_id, "Node ID" %>
  <%= form.text_field :node_id %>

  <%= form.label :pm_sensor_id, "PM Sensor ID" %>
  <%= form.text_field :pm_sensor_id %>

  <%= form.label :temp_rh_sensor_id, "Temp RH Sensor ID" %>
  <%= form.text_field :temp_rh_sensor_id %>

  <%= form.label :community_registration_id, "Community Registration ID" %>
  <%= form.text_field :community_registration_id %>

  <%= form.radio_button :active, true %>
  <%= form.label :active_true, "Active" %>
  <%= form.radio_button :active, false %>
  <%= form.label :active_false, "Inactive" %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sensors/edit.html.erb
<h1>Editing Sensor</h1>

<%= render 'form', sensor: @sensor %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

app/views/sensors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sensors</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensors.each do |sensor| %>
      <tr>
        <td><%= sensor.label %></td>
        <td><%= sensor.active ? 'active' : 'inactive' %></td>
        <td><%= link_to 'Show', sensor %></td>
        <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
        <td><%= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sensor', new_sensor_path %>

app/views/sensors/new.html.erb
<h1>New Sensor</h1>

<%= render 'form', sensor: @sensor %>

<%= link_to 'Back', sensors_path %>

app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<ul>
  <li><%= @sensor.id %></li>
  <li><%= @sensor.label %></li>
  <li><%= @sensor.model %></li>
  <li><%= @sensor.node_id %></li>
  <li><%= @sensor.pm_sensor_id %></li>
  <li><%= @sensor.temp_rh_sensor_id %></li>
  <li><%= @sensor.community_registration_id %></li>
  <li><%= @sensor.active ? 'active' : 'inactive' %></li>
</ul>
<%= link_to 'Edit', edit_sensor_path(@sensor) %> |
<%= link_to 'Back', sensors_path %>